name: Ansible Deployment

on:
  workflow_dispatch:
    inputs:
      ec2_ip_address:
        description: "Enter the EC2 instance IP address"
        required: true
        default: ""
      security_group_id:
        description: "Enter the Security Group ID to update"
        required: true
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible
      shell: bash

    # - name: Debug SSH Private Key
    #   run: echo "${{ secrets.TLS_CERTIFICATE }}"
    #   shell: bash

    - name: Write SSH Private Key to File
      run: echo "${{ secrets.TLS_CERTIFICATE }}" | 'tr -d '\r' > /tmp/private_key.pem
      shell: bash

    - name: Set Permissions on Private Key
      run: chmod 600 /tmp/private_key.pem

    - name: Verify Private Key File Exists
      run: ls -l /tmp/private_key.pem && cat /tmp/private_key.pem | head -n 5
      shell: bash

    - name: Get GitHub Runner IP
      id: get_ip
      run: |
        IP=$(curl -s https://api.ipify.org/)
        echo "RUNNER_IP=$IP" >> $GITHUB_ENV
      shell: bash

    - name: Update Security Group with Runner IP
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ github.event.inputs.security_group_id }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ env.RUNNER_IP }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2

    - name: Ensure .ssh Directory Exists
      run: mkdir -p ~/.ssh
      shell: bash

    - name: Add EC2 Host Key to Known Hosts
      run: |
        ssh-keyscan -H ${{ github.event.inputs.ec2_ip_address }} >> ~/.ssh/known_hosts
      shell: bash
    
    - name: Create Ansible Inventory
      run: |
        echo "[web_servers]" > ansible/inventory
        echo "${{ github.event.inputs.ec2_ip_address }} ansible_ssh_private_key_file=/tmp/private_key.pem ansible_user=ubuntu" >> ansible/inventory
      shell: bash

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory ansible/playbook.yml
      env:
        ANSIBLE_CONFIG: ansible/ansible.cfg
