name: Generate TLS Certificates

# Trigger this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.5

    - name: Initialize Terraform
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Apply Terraform - Generate TLS Certificates
      run: terraform apply -auto-approve -target=tls_private_key.ssh_key
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Output Private Key
      run: |
        echo "Private Key:"
        echo "${{ steps.apply.outputs.private_key }}"
      env:
        PRIVATE_KEY: ${{ steps.apply.outputs.private_key }}
    